apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: webserver-pvc
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: webserver
    spec:
      containers:
      - name: webserver
        image: nginx:alpine
        ports:
        - containerPort: 80
        volumeMounts:
        - name: hostvol
          mountPath: /usr/share/nginx/html
      volumes:
      - name: hostvol
        persistentVolumeClaim:
          claimName: localclaim