apiVersion: v1
kind: PersistentVolume
metadata:
  name: localvol
spec:
  capacity:
    storage: 500Mi
  accessModes:
    - ReadWriteMany
  storageClassName: local-store
  hostPath:
    path: "/sharehtml"
